/**
 * 
 */
package ch.ethz.matsim.supernetwork.simulation_data.traffic_data.container;

import org.matsim.api.core.v01.Id;
import org.matsim.vehicles.Vehicle;

import com.google.inject.Inject;




/**
 * @author stefanopenazzi
 *
 */
public class LinkDataTTV implements LinkData{
	
	private int time;
	 //0 if this is generated by LinkLeaveEventHandler, LinkEnterEventHandler,
	 //1 if this is generated by VehicleEntersTrafficEventHandler,VehicleLeavesTrafficEventHandler
	private boolean type;
	
	private Id<Vehicle> id;
	
	@Inject
	public LinkDataTTV() {}
	
	public LinkDataTTV(int time, boolean type,Id<Vehicle> id) {
		this.time = time;
		this.type = type;
		this.id = id;
	}
	public int getTime() {
		return this.time;
	}
	public boolean getType() {
		return this.type;
	}
	
	public Id<Vehicle> getId(){
		return this.id;
	}
}

